#! python


def build(ctx):

    for data in 'claims_outlier', 'cpi_adjust', 'recent_table', 'szpiro_table':

        ctx(
            features='run_py_script',
            source='plot_trends.py',
            deps=ctx.path_to(ctx, 'OUT_DATA', '{}.csv'.format(data)),
            target=ctx.path_to(ctx, 'OUT_FIGURES', 'fig_{}.png'.format(data)),
            name='plot_trends.py',
            append=data
        )

    ctx(
        features='run_py_script',
        source='plot_cri.py',
        deps=ctx.path_to(ctx, 'OUT_DATA', 'szpiro_table.csv'),
        target=ctx.path_to(ctx, 'OUT_FIGURES', 'cri_fun_crra.png'),
        name='plot_cri.py'
    )


    from src.final.project_dependency_graph import make_project_dependency_graph

    ctx.add_post_fun(make_project_dependency_graph)
